### PR TITLE
Breaking

### PR DESCRIPTION
**Pull request by rowanmanning**
#79

### CODE REVIEW

**Comment by notlee** [comment]
Don't forget to check for cjs over esm use, the [list on the issue](https://github.com/Financial-Times/o-tabs/issues/79) is a little different

**Comment by origamiserviceuser** [comment]
o-tabs bundle size difference from 4.3.2 to f37449223517c266cb6151a6879d534fe9d68bbe
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-tabs bundle size difference from 4.3.2 to 30d48859c4d7f7d1140ed7f3fa67fb362d6b6ad6
js: 0.32kb increase (0.11kb/gzip)
css, master: 1.29kb increase (0.17kb/gzip)
css, internal: 1.29kb increase (0.17kb/gzip)
css, whitelabel: 1.51kb increase (0.19kb/gzip)

**Comment by origamiserviceuser** [comment]
o-tabs bundle size difference from 4.3.2 to 52577c308d82e44801ee46d2db4081c4dfe9ef9f
js: 0.28kb increase (0.09kb/gzip)
css, master: 1.24kb increase (0.16kb/gzip)
css, internal: 1.24kb increase (0.15kb/gzip)
css, whitelabel: 1.46kb increase (0.17kb/gzip)

**Pull request merged**
